# Generated by Django 3.2.5 on 2021-07-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='departement',
            field=models.CharField(choices=[('OUEST', 'Ouest'), ("GRAND'ANSE", "Grand'anse"), ('SUD', 'Sud'), ('NORD', 'Nord'), ('NORD OUEST', 'Nord ouest'), ('NORD EST', 'Nord est'), ('SUD OUEST', 'Sud ouest'), ('ARTIBONITE', 'Artibonite'), ('CENTRE', 'Centre'), ('NIPPES', 'Nippes')], default='Ouest', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='pays',
            field=models.CharField(choices=[('HAITI', 'haiti'), ('AUTRE', 'autre')], default='haiti', max_length=10),
        ),
    ]
