# Generated by Django 3.2.5 on 2021-07-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_auto_20210723_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assurance',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Nom')], default='Non', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexe',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('AUTRE', 'Autre')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('CHOMAGE', 'Chomage'), ('PROFESSIONEL', 'Professionel')], default='Chomage', max_length=200),
        ),
    ]
