# Generated by Django 3.2.5 on 2021-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0012_alter_profile_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assurance',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Non', max_length=10),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(null=True, related_name='Profession', to='profil.Profession'),
        ),
    ]
