# Generated by Django 3.2.5 on 2021-07-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0024_auto_20210727_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
