# Generated by Django 3.2.5 on 2021-07-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0026_image_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='profile',
            new_name='user',
        ),
    ]
