# Generated by Django 3.2.5 on 2021-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0030_alter_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
