# Generated by Django 3.2.5 on 2021-07-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'Specialities'},
        ),
        migrations.AlterField(
            model_name='speciality',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
