# Generated by Django 3.2.5 on 2021-07-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210723_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinique',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hopital',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
